### ISSUE TITLE
Unable to open the project in Eclipse

### ISSUE THREAD

**Issue by chamander** [kevindang97/sudoku#1]
After cloning the project, I noticed that there isn't a `.project` file in the directory, which I think is something I need to open the project in Eclipse.

It looks like it was set to be ignored by Git in cd89e2c. Is there some other way that I should be able to open the project, perhaps in some other IDE?

**Comment by kevindang97** [comment]
You should be able to import it as a Maven project using Eclipse.

Within Eclipse, if you go to File -> Import -> Existing Maven Project and then select the sudoku folder it should import fine. If it's not working from there I'll try and fix whatever the problem is.

**Comment by chamander** [comment]
Great! That worked out. Does adding that to the documentation as some form of set up information sound like some work that can be done?

**Comment by kevindang97** [comment]
Awesome! And I've added this info now into the README.md

**Comment by chamander** [comment]
I've opened a pull request, #2. Would you be able to let me know if you think it's too elongated, or can otherwise be made more succinct?
